### PR TITLE
Finalize GHA migration

### PR DESCRIPTION
**Pull request by robbecker-wf**
# Summary
Finalize the migration to Github Actions for CI while also maintaining dependency tracking for Workiva.

# Changes
- removes Dockerfile
- added Software Bill of Materials (SBOM) generation
- Updated permissions to the ones needed to run SBOM generation

# QA
- GHA CI passes
- Workiva Build will fail since Dockerfile is removed, but this is intended and ok to merge with the failure
- the cyclone.dx file is included as an artifact on the github job summary

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by robbecker-wf** [comment]
QA+1 CI passes for GHA
image
the cyclone file is an artifact on the build

**Review by matthewnitschke-wk — APPROVED** [review]

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p go for it

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
