### PR TITLE
Scan for Pubspec on Save

### PR DESCRIPTION
**Pull request by joebingham-wk**
## Motivation

The extension doesn't look for nested `pubspec.yaml` files. This is an issue when the root of the project has none or a nested dart_dev config relies on one. This PR fixes that!

## Changes
- Change `getProjectPath` to scan for a `pubspec.yaml` file rather than a `tool` directory. This makes more sense as I'd expect a nested dart_dev config would also have it's own pubspec, but me know if this isn't a safe assumption. In other words, if that can't be assumed, this may break the tool scanning functionality. Otherwise, it should be safe.
- Parse the pubspec on the first document save. This provides the chance to use the targeted file path to look for a nested pubspec.yaml (aka a nested project). 
  - This step also now caches the current package path and will only re-parse the pubspec if the package path changes. Consequently, you'll still need to restart in order to bump pubspec versions unless you have a nested package to reset that cached value.

## QA
- [ ] Verify that the extension works in the following environments using the .vsix file installation method (with the .vsix in this PR). "Extension works" means:
  - [ ] Runs `dartfmt` in a project without an `over_react_format` dependency (or too old of a version)
  - [ ] Runs `over_react_format` in a project with an `over_react_format` dependency
  - [ ] Uses the config from the nearest root with a `tool/` dir if there are multiple in the open project
  - [ ] Detects the `pubspec` closest to the file that triggered the formatter
  - [ ] Correctly switches packages if a `pubspec` was detected for a different package in the project

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by joebingham-wk** [comment]
Hmm just realized this does impact some consumers who have nested pubspec.yaml files in their app directory with no corresponding tool directories (but their project root does have a tool directory that formats the app directory). This would force them to have to create a tool directory in the app directory to get the expected behavior, which would be a breaking change. I'm adding a configuration option to make this change opt in!

**Comment by todbachman-wf** [comment]
+10

### Testing Performed:
  - [x] Runs `dartfmt` in a project without an `over_react_format` dependency (or too old of a version)
  - [x] Runs `over_react_format` in a project with an `over_react_format` dependency
  - [x] Uses the config from the nearest root with a `tool/` dir if there are multiple in the open project
  - [x] Detects the `pubspec` closest to the file that triggered the formatter
  - [x] Correctly switches packages if a `pubspec` was detected for a different package in the project

**Comment by joebingham-wk** [comment]
@Workiva/release-management-p

**Pull request merged**
