### PR TITLE
Use dart executable instead of pub

### PR DESCRIPTION
**Pull request by joebingham-wk**
## Motivation

We just adopt Dart 2.18 and with that, `pub` is no longer an executable. This PR switches it to `dart` so that consumers don't need a `pub` alias.

## Changes

- Switch from `pub` executable to `dart`
- Rebuild the extension as v1.0.2

## QA'ing
- [ ] Install the package and verify it works with Dart 2.18
    - Clone this repo
    - In the repo, run `code --install-extension over-react-format-on-save-1.0.2.vsix`
    - Your VS Code OverReach Format on Save extension should be v1.0.2 now. 
        - If it's not, you can run remove the v1.0.1 (or whatever version) from the extensions directory (`~/.vscode/extensions`), and it your IDE should use v1.0.2
    - Open a project in VS Code, being sure you're using Dart 2.18
    - Verify formatting works as expected

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by annawatson-wk — APPROVED** [review]

**Review by annawatson-wk — APPROVED** [review]
QA +1, formats as expected

**Comment by annawatson-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
